FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# go-online

go-online is a simple online application which allows people code, run and test anywhere.
 
## Project Collection [/{projectname}]

### Get project file structure [GET /{projectid}]

Get file structure with given projectid

+ Parameters
    + projectid: 1 (string) - Specified the project id
    
+ Response 200 (application)

        [
            {
                "id": 1,
                "name": "file1",
                "edit_status": 0,
                "type": "file"
            },
            {
                "id": 2,
                "name": "dir1",
                "edit_status": 0,
                "type": "dir",
                "children": [
                    {
                        "id": 3,
                        "name": "file2",
                        "edit_status": 0,
                        "type": "file"
                    }
                ]
            }
        ]
        
### Get file content [GET /{projectid}/tree/{filepath}]

Get file content with given and file path

+ Parameters
    + projectid: 1 (string) - Specified the project id
    + filepath: "a/b/a" (string) - Specified the relative path with the project root
    
+ Response 200 (plain/text)

        "Here is the content of the required file"
        
### Upload file content [POST /{projectid}/tree/{filepath}]

Upload file content with given file path

+ Parameters
    + projectid: 1 (string) - Specified the project id
    + filepath: "a/b/a" (string) - Specified the relative path with the project root
   
+ Request

    + Body
    
            "Here is the content of the file required to be updated"

+ Response 200

## Command Collection [/ws]

### Init a connection

We should note that this collection uses ws to communicate with each other, so I can not show the IO with this document.
In general, the front end init a ws connection with server, and there should include some validation message in there's header.
All the message in a connection is a part of the initial command and once the connection was shutted down, it means the resources should be released.
A user can use one command now, and he can use one connection , that is , one docker container at the same time.