-- MySQL Script generated by MySQL Workbench
-- Thu May 24 10:09:06 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `create_time` DATETIME NOT NULL,
  `gender` INT NULL,
  `age` INT NULL,
  `token` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NULL,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`username`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `language` INT NOT NULL,
  `create_time` DATETIME NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `users_username`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_projects_users1_idx` (`users_username` ASC),
  CONSTRAINT `fk_projects_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `mydb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hub_name` VARCHAR(45) NOT NULL,
  `label` VARCHAR(45) NULL DEFAULT 'latest',
  `users_username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `users_username`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_images_users1_idx` (`users_username` ASC),
  CONSTRAINT `fk_images_users1`
    FOREIGN KEY (`users_username`)
    REFERENCES `mydb`.`users` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`golang_setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`golang_setting` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `gopath` VARCHAR(45) NULL DEFAULT '/go',
  `version` VARCHAR(45) NULL DEFAULT '1.9.0',
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`id`, `projects_id`),
  INDEX `fk_golang_setting_projects1_idx` (`projects_id` ASC),
  CONSTRAINT `fk_golang_setting_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `mydb`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
